---
title: "soybean_WGD"
output: html_document
date: "2024-10-03"
---

```{r load the libraries}
library(dplyr)
library(ggplot2)
library(tidyr)
library(stringr)
```

```{r duplicated gene pairs}
#load the gene pairs generated by the DupGene_finder 
wgd<-read.delim2("glyma.wgd.pairs_no_scaffold")
wgd$duplication_status<-rep("WGD",29905)
wgd<-wgd %>%
  distinct()

td<-read.delim2("glyma.tandem.pairs_no_scaffold")
td$duplication_status<-rep("TD",1749)
td<-td %>%
  distinct()

pd<-read.delim2("glyma.proximal.pairs_no_scaffold")
pd$duplication_status<-rep("PD",1942)
pd<-pd %>%
  distinct()


trd<-read.delim2("glyma.transposed.pairs_no_scaffold.txt")
trd$duplication_status<-rep("TRD",3275)
colnames(trd)<-colnames(wgd)
trd<-trd %>%
  distinct()


dsd<-read.delim2("glyma.dispersed.pairs_no_scaffold.txt")
dsd$duplication_status<-rep("DSD",22517)
dsd<-dsd %>%
  distinct()

glyma_duplicated_pairs<-rbind(wgd,td,pd,trd,dsd)

#check whether there are duplicated rows in the file  
glyma_duplicated_pairs_unique<-glyma_duplicated_pairs[!duplicated(glyma_duplicated_pairs),]
glyma_duplicated_pairs_duplicated<-glyma_duplicated_pairs[duplicated(glyma_duplicated_pairs),]

#rename the gene ID for glyma 
glyma_duplicated_pairs<- glyma_duplicated_pairs %>%
  mutate(
    duplicate_1 = str_extract(Duplicate.1, "Glyma\\.\\d{2}G\\d{6}"),
    duplicate_2 = str_extract(Duplicate.2, "Glyma\\.\\d{2}G\\d{6}")
  )

#summarise the amount of the different duplicate pairs for each catagory 
summary_glyma_duplicated_pairs_unique_counts <- glyma_duplicated_pairs_unique %>%
  count(duplication_status)

singleton<-read.delim2("glyma.singletons_no_scaffold.txt")
singleton<-singleton %>%
  mutate(
    GeneID_new = str_extract(GeneID, "Glyma\\.\\d{2}G\\d{6}")
  ) %>%
  select(GeneID_new, Location) %>%
  distinct()

all_gene<-read.delim2("glyma.gff.txt", header = FALSE)
colnames(all_gene) <- c("chromsome","gene_id","start","end")

all_gene <- all_gene %>%
    mutate(
    GeneID_new = str_extract(gene_id, "Glyma\\.\\d{2}G\\d{6}")
  ) %>%
  select(chromsome, GeneID_new, start, end) %>%
  distinct()
  
(66070-25769)/66070

glyma_duplicated_pairs_final <- glyma_duplicated_pairs %>%
  select(duplicate_1,Location,duplicate_2,Location.1,E.value, duplication_status)

write.csv(glyma_duplicated_pairs, "07042025_glyma_duplicated_pairs.csv")

```


```{r duplicated genes}
#summary the genes, originating from different categories 
Duplicate1<-glyma_duplicated_pairs_unique[,c("Duplicate.1","duplication_status")]
colnames(Duplicate1) <- c("Dup","duplication_status")
Duplicate2<-glyma_duplicated_pairs_unique[,c("Duplicate.2","duplication_status")]
colnames(Duplicate2) <- c("Dup","duplication_status")
Duplicated_genes<-rbind(Duplicate1,Duplicate2)

#summary the genes, removing the duplicates 
Duplicated_genes_wgd<-Duplicated_genes[Duplicated_genes$duplication_status == "WGD",]
Duplicated_genes_wgd_unique<-unique(Duplicated_genes_wgd)

Duplicated_genes_td<-Duplicated_genes[Duplicated_genes$duplication_status == "TD",]
Duplicated_genes_td_unique<-unique(Duplicated_genes_td)

Duplicated_genes_pd<-Duplicated_genes[Duplicated_genes$duplication_status == "PD",]
Duplicated_genes_pd_unique<-unique(Duplicated_genes_pd)

Duplicated_genes_trd<-Duplicated_genes[Duplicated_genes$duplication_status == "TRD",]
Duplicated_genes_trd_unique<-unique(Duplicated_genes_trd)

Duplicated_genes_dsd<-Duplicated_genes[Duplicated_genes$duplication_status == "DSD",]
Duplicated_genes_dsd_unique<-unique(Duplicated_genes_dsd)

Duplicated_genes_unique <- Duplicated_genes[!duplicated(Duplicated_genes$Dup), ]

write.csv(Duplicated_genes_unique, "Duplicated_genes_unique.csv")
write.csv(Duplicated_genes, "Duplicated_genes_all.csv")

#write.csv(Duplicated_genes_dsd_unique, "Duplicated_genes_dsd_unique.csv")
#write.csv(Duplicated_genes_td_unique, "Duplicated_genes_td_unique.csv")
#write.csv(Duplicated_genes_pd_unique, "Duplicated_genes_pd_unique.csv")
#write.csv(Duplicated_genes_trd_unique, "Duplicated_genes_trd_unique.csv")
#write.csv(Duplicated_genes_wgd_unique, "Duplicated_genes_wgd_unique.csv")


glyma_genes<-read.delim2("glyma_gene_list", header=FALSE)
colnames(glyma_genes) <- "Dup"

sc <- glyma_genes %>% anti_join(Duplicated_genes_unique, by = "Dup")
#write.csv(sc,"sc_genes.csv")
```

