---
title: "characterize_duplicated_gene_pairs"
output: html_document
date: "2024-12-13"
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(tidyr)
library(purrr)
library(patchwork)

duplicated_gene_pairs<-read.csv("07182025_duplicated_gene_pairs.csv")
duplicated_gene_pairs <- duplicated_gene_pairs %>%
  mutate (Gene_Pair = paste(duplicate_1,duplicate_2, sep = " vs "))

duplicated_gene_pairs_percentage <- duplicated_gene_pairs %>%
  group_by(type) %>%
  summarise(count = n(), .groups = 'drop') %>%
  mutate(percentage = count / sum(count) )

```


```{r early_nodule}
#load the data from last step, fold change calculation using the gene pairs at least one gene expressed 
early_nodule_filter<-read.csv("set_early_nodule_filter_paralog_pair_coexpression_fold_change.csv")

#load the normalized gene expression of gene pairs across different cell types within the tissue, this is the normalized data 
#early_nodule_filter_expression<-read.csv("07152025_expressed_early_nodule_filtere_pairs_expression_separated_raw.csv")

#the gene pairs with fold change is equal to NA is the gene pairs with one gene expressed while the other not expressed
early_nodule_filter_one_express<-early_nodule_filter %>%
  filter(is.na(coexpression))

#assign the expression type to these gene pairs, one expressed while the other not 
early_nodule_filter_one_express$expression_type<-"mono_expressed"

#extract the other types of expression patterns using fold change and coexpression information 
early_nodule_filter_dosage_balance<-early_nodule_filter %>%
  filter(coexpression > 0.9,
        log2FC_mean_tissue <1,
        log2FC_sd_tissue <1)

early_nodule_filter_paralogue_dominance<-early_nodule_filter %>%
  filter(coexpression > 0.9,
        log2FC_mean_tissue >= 1,
        log2FC_sd_tissue <1)

early_nodule_filter_specialized<-early_nodule_filter %>%
  filter(coexpression > 0.9,
        log2FC_mean_tissue >= 1,
        log2FC_sd_tissue >=1)

early_nodule_filter_diverged<-early_nodule_filter %>%
  filter(coexpression < 0.5,
        log2FC_mean_tissue >= 1,
        log2FC_sd_tissue >=1)

#assign the expression type to these gene pairs 
early_nodule_filter_dosage_balance$expression_type<-"dosage_balance"
early_nodule_filter_paralogue_dominance$expression_type<-"paralogue_dominance"
early_nodule_filter_specialized$expression_type<-"specialized"
early_nodule_filter_diverged$expression_type<-"diverged"

early_nodule_expression_type<-rbind(early_nodule_filter_dosage_balance, early_nodule_filter_paralogue_dominance, early_nodule_filter_specialized, early_nodule_filter_diverged, early_nodule_filter_one_express)

#extract the gene pairs not included in any of above expression type but at least one gene expressed
early_nodule_other_expression_type<- anti_join(early_nodule_filter,early_nodule_expression_type, by= "Gene_Pair")
early_nodule_other_expression_type$expression_type<-"others"

#extract the gene pairs not expressed in this tissue 
early_nodule_not_expressed<-anti_join(duplicated_gene_pairs,early_nodule_filter, by="Gene_Pair")

#focus on the gene pairs with different expression types 

#this object includes the gene pairs expressed but with different expression patterns 
early_nodule_expression_type_final<-rbind(early_nodule_expression_type,early_nodule_other_expression_type)
early_nodule_expression_type_final<-left_join(early_nodule_expression_type_final, duplicated_gene_pairs, by="Gene_Pair")

#this object includes all the gene pairs, including both expressed and not expressed ones
early_nodule_expression_type_final_all<-left_join(duplicated_gene_pairs,early_nodule_expression_type_final, by="Gene_Pair")
early_nodule_expression_type_final_all$expression_type[is.na(early_nodule_expression_type_final_all$expression_type)] <- "not_expressed"

early_nodule_summary_expression_duplication <- early_nodule_expression_type_final_all %>%
  group_by(type.x,expression_type) %>%
  summarise(count = n(), .groups = 'drop')  %>%
  group_by(type.x) %>%
  mutate(percentage = count / sum(count))

early_nodule_summary_duplication <- early_nodule_expression_type_final_all %>%
  group_by(expression_type,type.x) %>%
  summarise(count = n(), .groups = 'drop')  %>%
  group_by(expression_type) %>%
  mutate(percentage = count / sum(count))

early_nodule_summary_expression <- early_nodule_expression_type_final_all %>%
  group_by(expression_type) %>%
  summarise(count = n(), .groups = 'drop')  %>%
  group_by(expression_type) %>%
  mutate(percentage = count /11424)


# Summary statistics by type
early_nodule_summary_stats <- early_nodule_expression_type_final %>%
  group_by(type) %>%
  summarise(
    coexpression_mean = mean(coexpression, na.rm = TRUE),
    coexpression_sd = sd(coexpression, na.rm = TRUE),
    log2FC_mean_mean = mean(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_mean_sd = sd(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_sd_mean = mean(log2FC_sd_tissue, na.rm = TRUE),
    log2FC_sd_sd = sd(log2FC_sd_tissue, na.rm = TRUE),
    .groups = 'drop'
  )

color_palette <- c("#7dabcf", "#cfe7eb")


ggplot(early_nodule_expression_type_final, aes(x = type, y = coexpression, fill = type)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
    scale_fill_manual(values = color_palette) +
  theme_minimal() +
  labs(title = "Coexpression by Duplication Type", y = "Coexpression", x = "Duplication Type")

ggplot(early_nodule_expression_type_final, aes(x = type, y = log2FC_mean_tissue, fill = type)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
    scale_fill_manual(values = color_palette) +
  theme_minimal() +
  labs(title = "Mean log2FC by Duplication Type", y = "Mean log2FC", x = "Duplication Type")


ggplot(early_nodule_expression_type_final, aes(x = type, y = log2FC_sd_tissue, fill = type)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
    scale_fill_manual(values = color_palette) +
  theme_minimal() +
  labs(title = "log2FC SD by Duplication Type", y = "log2FC SD", x = "Duplication Type")




early_nodule_expression_type_final_all_summary_set <- early_nodule_expression_type_final_all %>% 
  group_by(fam.x) %>%
  summarise(
    count_not_expressed = sum(expression_type == "not_expressed", na.rm = TRUE),
    count_mono_expressed = sum(expression_type == "mono_expressed", na.rm = TRUE),
    has_recent_WGD_in_not_expressed = any(expression_type == "not_expressed" & type.x == "recent_WGD", na.rm = TRUE),
    coexpression_mean = mean(coexpression, na.rm = TRUE),
    coexpression_sd = sd(coexpression, na.rm = TRUE),
    log2FC_mean_mean = mean(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_mean_sd = sd(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_sd_mean = mean(log2FC_sd_tissue, na.rm = TRUE),
    log2FC_sd_sd = sd(log2FC_sd_tissue, na.rm = TRUE),
    .groups = 'drop'
  ) %>%
  mutate(
    set_expression = case_when(
      count_not_expressed == 6 & count_mono_expressed == 0 ~ "not expressed",
      count_not_expressed == 0 & count_mono_expressed == 3 ~ "three expressed",
      count_not_expressed == 1 & count_mono_expressed == 4 ~ "two expressed",
      count_not_expressed == 3 & count_mono_expressed == 3 ~ "one expressed",
      count_not_expressed == 0 & count_mono_expressed == 0 ~ "four expressed",
      TRUE ~ "other"
    ),
    set_expression = ifelse(
      set_expression == "two expressed" & has_recent_WGD_in_not_expressed,
      "recent_WGD_non_expressed",
      set_expression
    )
  )

write.csv(early_nodule_expression_type_final_all_summary_set, "0829_early_nodule_expression_type_final_all_summary_set.csv")


summary_of_early_nodule_expression_type_final_all_summary_set <- early_nodule_expression_type_final_all_summary_set %>%
  count(set_expression, name = "family_count")

print(summary_of_early_nodule_expression_type_final_all_summary_set)



early_nodule_set_expression_summary_stats <- early_nodule_expression_type_final_all_summary_set %>%
  group_by(set_expression) %>%
  summarise(
    n_families = n(),
    coexpression_mean = mean(coexpression_mean, na.rm = TRUE),
    coexpression_sd = sd(coexpression_mean, na.rm = TRUE),
    log2FC_mean_mean = mean(log2FC_mean_mean, na.rm = TRUE),
    log2FC_mean_sd = sd(log2FC_mean_mean, na.rm = TRUE),
    log2FC_sd_mean = mean(log2FC_sd_mean, na.rm = TRUE),
    log2FC_sd_sd = sd(log2FC_sd_mean, na.rm = TRUE),
    .groups = 'drop'
  )


color_palette <- c("#7dabcf", "#cfe7eb")

p1 <- ggplot(early_nodule_expression_type_final_all_summary_set, aes(x = set_expression, y = coexpression_mean, fill = set_expression)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA) +

  labs(title = "Coexpression Mean by Set Expression", y = "Mean Coexpression", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


p2 <- ggplot(early_nodule_expression_type_final_all_summary_set, aes(x = set_expression, y = log2FC_mean_mean, fill = set_expression)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA) +

  labs(title = "log2FC Mean by Set Expression", y = "Mean log2FC", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p3 <- ggplot(early_nodule_expression_type_final_all_summary_set, aes(x = set_expression, y = log2FC_sd_mean, fill = set_expression)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA) +

  labs(title = "log2FC SD by Set Expression", y = "SD of log2FC", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p1 / p2 / p3

```


```{r cotyledon}
#load the data from last step, fold change calculation using the gene pairs at least one gene expressed 
cotyledon_filter<-read.csv("set_cotyledon_filter_paralog_pair_coexpression_fold_change.csv")

#load the normalized gene expression of gene pairs across different cell types within the tissue
#cotyledon_filter_expression<-read.csv("07152025_expressed_cotyledon_filtere_pairs_expression_separated_raw.csv")

#the gene pairs with fold change is equal to NA is the gene pairs with one gene expressed while the other not expressed
cotyledon_filter_one_express<-cotyledon_filter %>%
  filter(is.na(coexpression))

#assign the expression type to these gene pairs, one expressed while the other not 
cotyledon_filter_one_express$expression_type<-"mono_expressed"

#extract the other types of expression patterns using fold change and coexpression information 
cotyledon_filter_dosage_balance<-cotyledon_filter %>%
  filter(coexpression > 0.9,
        log2FC_mean_tissue <1,
        log2FC_sd_tissue <1)

cotyledon_filter_paralogue_dominance<-cotyledon_filter %>%
  filter(coexpression > 0.9,
        log2FC_mean_tissue >= 1,
        log2FC_sd_tissue <1)

cotyledon_filter_specialized<-cotyledon_filter %>%
  filter(coexpression > 0.9,
        log2FC_mean_tissue >= 1,
        log2FC_sd_tissue >=1)

cotyledon_filter_diverged<-cotyledon_filter %>%
  filter(coexpression < 0.5,
        log2FC_mean_tissue >= 1,
        log2FC_sd_tissue >=1)

#assign the expression type to these gene pairs 
cotyledon_filter_dosage_balance$expression_type<-"dosage_balance"
cotyledon_filter_paralogue_dominance$expression_type<-"paralogue_dominance"
cotyledon_filter_specialized$expression_type<-"specialized"
cotyledon_filter_diverged$expression_type<-"diverged"

cotyledon_expression_type<-rbind(cotyledon_filter_dosage_balance, cotyledon_filter_paralogue_dominance, cotyledon_filter_specialized, cotyledon_filter_diverged, cotyledon_filter_one_express)

#extract the gene pairs not included in any of above expression type but both genes expressed 
cotyledon_other_expression_type<- anti_join(cotyledon_filter,cotyledon_expression_type, by= "Gene_Pair")
cotyledon_other_expression_type$expression_type<-"others"

#extract the gene pairs not expressed in this tissue 
cotyledon_not_expressed<-anti_join(duplicated_gene_pairs,cotyledon_filter, by="Gene_Pair")

#focus on the gene pairs with different expression types 

#this object includes the gene pairs expressed but with different expression patterns 
cotyledon_expression_type_final<-rbind(cotyledon_expression_type,cotyledon_other_expression_type)
cotyledon_expression_type_final<-left_join(cotyledon_expression_type_final, duplicated_gene_pairs, by="Gene_Pair")

#this object includes all the gene pairs, including both expressed and not expressed ones
cotyledon_expression_type_final_all<-left_join(duplicated_gene_pairs,cotyledon_expression_type_final, by="Gene_Pair")
cotyledon_expression_type_final_all$expression_type[is.na(cotyledon_expression_type_final_all$expression_type)] <- "not_expressed"

cotyledon_summary_expression_duplication <- cotyledon_expression_type_final_all %>%
  group_by(type.x,expression_type) %>%
  summarise(count = n(), .groups = 'drop')  %>%
  group_by(type.x) %>%
  mutate(percentage = count / sum(count))

cotyledon_summary_duplication <- cotyledon_expression_type_final_all %>%
  group_by(expression_type,type.x) %>%
  summarise(count = n(), .groups = 'drop')  %>%
  group_by(expression_type) %>%
  mutate(percentage = count / sum(count))

cotyledon_summary_expression <- cotyledon_expression_type_final_all %>%
  group_by(expression_type) %>%
  summarise(count = n(), .groups = 'drop')  %>%
  group_by(expression_type) %>%
  mutate(percentage = count /11424)

#write.csv(cotyledon_expression_type_final_all , "presentation_cotyledon_expression_type_final_all.csv")


# Summary statistics by type
cotyledon_summary_stats <- cotyledon_expression_type_final %>%
  group_by(type) %>%
  summarise(
    coexpression_mean = mean(coexpression, na.rm = TRUE),
    coexpression_sd = sd(coexpression, na.rm = TRUE),
    log2FC_mean_mean = mean(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_mean_sd = sd(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_sd_mean = mean(log2FC_sd_tissue, na.rm = TRUE),
    log2FC_sd_sd = sd(log2FC_sd_tissue, na.rm = TRUE),
    .groups = 'drop'
  )

ggplot(cotyledon_expression_type_final, aes(x = type, y = coexpression, fill = type)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
    scale_fill_manual(values = color_palette) +
  theme_minimal() +
  labs(title = "Coexpression by Duplication Type", y = "Coexpression", x = "Duplication Type")

ggplot(cotyledon_expression_type_final, aes(x = type, y = log2FC_mean_tissue, fill = type)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
    scale_fill_manual(values = color_palette) +
  theme_minimal() +
  labs(title = "Mean log2FC by Duplication Type", y = "Mean log2FC", x = "Duplication Type")


ggplot(cotyledon_expression_type_final, aes(x = type, y = log2FC_sd_tissue, fill = type)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
    scale_fill_manual(values = color_palette) +
  theme_minimal() +
  labs(title = "log2FC SD by Duplication Type", y = "log2FC SD", x = "Duplication Type")

cotyledon_expression_type_final_all_summary_set <- cotyledon_expression_type_final_all %>% 
  group_by(fam.x) %>%
  summarise(
    count_not_expressed = sum(expression_type == "not_expressed", na.rm = TRUE),
    count_mono_expressed = sum(expression_type == "mono_expressed", na.rm = TRUE),
    has_recent_WGD_in_not_expressed = any(expression_type == "not_expressed" & type.x == "recent_WGD", na.rm = TRUE),
    coexpression_mean = mean(coexpression, na.rm = TRUE),
    coexpression_sd = sd(coexpression, na.rm = TRUE),
    log2FC_mean_mean = mean(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_mean_sd = sd(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_sd_mean = mean(log2FC_sd_tissue, na.rm = TRUE),
    log2FC_sd_sd = sd(log2FC_sd_tissue, na.rm = TRUE),
    .groups = 'drop'
  ) %>%
  mutate(
    set_expression = case_when(
      count_not_expressed == 6 & count_mono_expressed == 0 ~ "not expressed",
      count_not_expressed == 0 & count_mono_expressed == 3 ~ "three expressed",
      count_not_expressed == 1 & count_mono_expressed == 4 ~ "two expressed",
      count_not_expressed == 3 & count_mono_expressed == 3 ~ "one expressed",
      count_not_expressed == 0 & count_mono_expressed == 0 ~ "four expressed",
      TRUE ~ "other"
    ),
    set_expression = ifelse(
      set_expression == "two expressed" & has_recent_WGD_in_not_expressed,
      "recent_WGD_non_expressed",
      set_expression
    )
  )


write.csv(cotyledon_expression_type_final_all_summary_set, "07302025_cotyledon_expression_type_final_all_summary_set.csv")
summary_of_cotyledon_expression_type_final_all_summary_set <- cotyledon_expression_type_final_all_summary_set %>%
  count(set_expression, name = "family_count")

print(summary_of_cotyledon_expression_type_final_all_summary_set)


cotyledon_set_expression_summary_stats <- cotyledon_expression_type_final_all_summary_set %>%
  group_by(set_expression) %>%
  summarise(
    n_families = n(),
    coexpression_mean = mean(coexpression_mean, na.rm = TRUE),
    coexpression_sd = sd(coexpression_mean, na.rm = TRUE),
    log2FC_mean_mean = mean(log2FC_mean_mean, na.rm = TRUE),
    log2FC_mean_sd = sd(log2FC_mean_mean, na.rm = TRUE),
    log2FC_sd_mean = mean(log2FC_sd_mean, na.rm = TRUE),
    log2FC_sd_sd = sd(log2FC_sd_mean, na.rm = TRUE),
    .groups = 'drop'
  )

p1 <- ggplot(cotyledon_expression_type_final_all_summary_set, aes(x = set_expression, y = coexpression_mean, fill = set_expression)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA) +
  labs(title = "Coexpression Mean by Set Expression", y = "Mean Coexpression", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


p2 <- ggplot(cotyledon_expression_type_final_all_summary_set, aes(x = set_expression, y = log2FC_mean_mean, fill = set_expression)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA) +
  labs(title = "log2FC Mean by Set Expression", y = "Mean log2FC", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p3 <- ggplot(cotyledon_expression_type_final_all_summary_set, aes(x = set_expression, y = log2FC_sd_mean, fill = set_expression)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA) +
  labs(title = "log2FC SD by Set Expression", y = "SD of log2FC", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p1 / p2 / p3
```


```{r heart}
#load the data from last step, fold change calculation using the gene pairs at least one gene expressed 
heart_filter<-read.csv("set_heart_filter_paralog_pair_coexpression_fold_change.csv")

#load the normalized gene expression of gene pairs across different cell types within the tissue
#heart_filter_expression<-read.csv("07152025_expressed_heart_filtere_pairs_expression_separated_raw.csv")

#the gene pairs with fold change is equal to NA is the gene pairs with one gene expressed while the other not expressed
heart_filter_one_express<-heart_filter %>%
  filter(is.na(coexpression))

#assign the expression type to these gene pairs, one expressed while the other not 
heart_filter_one_express$expression_type<-"mono_expressed"

#extract the other types of expression patterns using fold change and coexpression information 
heart_filter_dosage_balance<-heart_filter %>%
  filter(coexpression > 0.9,
        log2FC_mean_tissue <1,
        log2FC_sd_tissue <1)

heart_filter_paralogue_dominance<-heart_filter %>%
  filter(coexpression > 0.9,
        log2FC_mean_tissue >= 1,
        log2FC_sd_tissue <1)

heart_filter_specialized<-heart_filter %>%
  filter(coexpression > 0.9,
        log2FC_mean_tissue >= 1,
        log2FC_sd_tissue >=1)

heart_filter_diverged<-heart_filter %>%
  filter(coexpression < 0.5,
        log2FC_mean_tissue >= 1,
        log2FC_sd_tissue >=1)

#assign the expression type to these gene pairs 
heart_filter_dosage_balance$expression_type<-"dosage_balance"
heart_filter_paralogue_dominance$expression_type<-"paralogue_dominance"
heart_filter_specialized$expression_type<-"specialized"
heart_filter_diverged$expression_type<-"diverged"

heart_expression_type<-rbind(heart_filter_dosage_balance, heart_filter_paralogue_dominance, heart_filter_specialized, heart_filter_diverged, heart_filter_one_express)

#extract the gene pairs not included in any of above expression type but both genes expressed 
heart_other_expression_type<- anti_join(heart_filter,heart_expression_type, by= "Gene_Pair")
heart_other_expression_type$expression_type<-"others"

#extract the gene pairs not expressed in this tissue 
heart_not_expressed<-anti_join(duplicated_gene_pairs,heart_filter, by="Gene_Pair")

#focus on the gene pairs with different expression types 

#this object includes the gene pairs expressed but with different expression patterns 
heart_expression_type_final<-rbind(heart_expression_type,heart_other_expression_type)
heart_expression_type_final<-left_join(heart_expression_type_final, duplicated_gene_pairs, by="Gene_Pair")

#this object includes all the gene pairs, including both expressed and not expressed ones
heart_expression_type_final_all<-left_join(duplicated_gene_pairs,heart_expression_type_final, by="Gene_Pair")
heart_expression_type_final_all$expression_type[is.na(heart_expression_type_final_all$expression_type)] <- "not_expressed"

heart_summary_expression_duplication <- heart_expression_type_final_all %>%
  group_by(type.x,expression_type) %>%
  summarise(count = n(), .groups = 'drop')  %>%
  group_by(type.x) %>%
  mutate(percentage = count / sum(count))

heart_summary_duplication <- heart_expression_type_final_all %>%
  group_by(expression_type,type.x) %>%
  summarise(count = n(), .groups = 'drop')  %>%
  group_by(expression_type) %>%
  mutate(percentage = count / sum(count))

heart_summary_expression <- heart_expression_type_final_all %>%
  group_by(expression_type) %>%
  summarise(count = n(), .groups = 'drop')  %>%
  group_by(expression_type) %>%
  mutate(percentage = count /11424)

#write.csv(heart_expression_type_final_all , "presentation_heart_expression_type_final_all.csv")


# Summary statistics by type
heart_summary_stats <- heart_expression_type_final %>%
  group_by(type) %>%
  summarise(
    coexpression_mean = mean(coexpression, na.rm = TRUE),
    coexpression_sd = sd(coexpression, na.rm = TRUE),
    log2FC_mean_mean = mean(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_mean_sd = sd(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_sd_mean = mean(log2FC_sd_tissue, na.rm = TRUE),
    log2FC_sd_sd = sd(log2FC_sd_tissue, na.rm = TRUE),
    .groups = 'drop'
  )

ggplot(heart_expression_type_final, aes(x = type, y = coexpression, fill = type)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
  theme_minimal() +
  labs(title = "Coexpression by Duplication Type", y = "Coexpression", x = "Duplication Type")

ggplot(heart_expression_type_final, aes(x = type, y = log2FC_mean_tissue, fill = type)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
  theme_minimal() +
  labs(title = "Mean log2FC by Duplication Type", y = "Mean log2FC", x = "Duplication Type")


ggplot(heart_expression_type_final, aes(x = type, y = log2FC_sd_tissue, fill = type)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
  theme_minimal() +
  labs(title = "log2FC SD by Duplication Type", y = "log2FC SD", x = "Duplication Type")


heart_expression_type_final_all_summary_set <- heart_expression_type_final_all %>% 
  group_by(fam.x) %>%
  summarise(
    count_not_expressed = sum(expression_type == "not_expressed", na.rm = TRUE),
    count_mono_expressed = sum(expression_type == "mono_expressed", na.rm = TRUE),
    has_recent_WGD_in_not_expressed = any(expression_type == "not_expressed" & type.x == "recent_WGD", na.rm = TRUE),
    coexpression_mean = mean(coexpression, na.rm = TRUE),
    coexpression_sd = sd(coexpression, na.rm = TRUE),
    log2FC_mean_mean = mean(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_mean_sd = sd(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_sd_mean = mean(log2FC_sd_tissue, na.rm = TRUE),
    log2FC_sd_sd = sd(log2FC_sd_tissue, na.rm = TRUE),
    .groups = 'drop'
  ) %>%
  mutate(
    set_expression = case_when(
      count_not_expressed == 6 & count_mono_expressed == 0 ~ "not expressed",
      count_not_expressed == 0 & count_mono_expressed == 3 ~ "three expressed",
      count_not_expressed == 1 & count_mono_expressed == 4 ~ "two expressed",
      count_not_expressed == 3 & count_mono_expressed == 3 ~ "one expressed",
      count_not_expressed == 0 & count_mono_expressed == 0 ~ "four expressed",
      TRUE ~ "other"
    ),
    set_expression = ifelse(
      set_expression == "two expressed" & has_recent_WGD_in_not_expressed,
      "recent_WGD_non_expressed",
      set_expression
    )
  )


summary_of_heart_expression_type_final_all_summary_set <- heart_expression_type_final_all_summary_set %>%
  count(set_expression, name = "family_count")

print(summary_of_heart_expression_type_final_all_summary_set)



heart_set_expression_summary_stats <- heart_expression_type_final_all_summary_set %>%
  group_by(set_expression) %>%
  summarise(
    n_families = n(),
    coexpression_mean = mean(coexpression_mean, na.rm = TRUE),
    coexpression_sd = sd(coexpression_mean, na.rm = TRUE),
    log2FC_mean_mean = mean(log2FC_mean_mean, na.rm = TRUE),
    log2FC_mean_sd = sd(log2FC_mean_mean, na.rm = TRUE),
    log2FC_sd_mean = mean(log2FC_sd_mean, na.rm = TRUE),
    log2FC_sd_sd = sd(log2FC_sd_mean, na.rm = TRUE),
    .groups = 'drop'
  )

p1 <- ggplot(heart_expression_type_final_all_summary_set, aes(x = set_expression, y = coexpression_mean, fill = set_expression)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA) +
  labs(title = "Coexpression Mean by Set Expression", y = "Mean Coexpression", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


p2 <- ggplot(heart_expression_type_final_all_summary_set, aes(x = set_expression, y = log2FC_mean_mean, fill = set_expression)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA) +
  labs(title = "log2FC Mean by Set Expression", y = "Mean log2FC", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p3 <- ggplot(heart_expression_type_final_all_summary_set, aes(x = set_expression, y = log2FC_sd_mean, fill = set_expression)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA) +
  labs(title = "log2FC SD by Set Expression", y = "SD of log2FC", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p1 / p2 / p3

```


```{r globular}
#load the data from last step, fold change calculation using the gene pairs at least one gene expressed 
globular_filter<-read.csv("set_globular_filter_paralog_pair_coexpression_fold_change.csv")

#load the normalized gene expression of gene pairs across different cell types within the tissue
#globular_filter_expression<-read.csv("07152025_expressed_globular_filtere_pairs_expression_separated_raw.csv")

#the gene pairs with fold change is equal to NA is the gene pairs with one gene expressed while the other not expressed
globular_filter_one_express<-globular_filter %>%
  filter(is.na(coexpression))

#assign the expression type to these gene pairs, one expressed while the other not 
globular_filter_one_express$expression_type<-"mono_expressed"

#extract the other types of expression patterns using fold change and coexpression information 
globular_filter_dosage_balance<-globular_filter %>%
  filter(coexpression > 0.9,
        log2FC_mean_tissue <1,
        log2FC_sd_tissue <1)

globular_filter_paralogue_dominance<-globular_filter %>%
  filter(coexpression > 0.9,
        log2FC_mean_tissue >= 1,
        log2FC_sd_tissue <1)

globular_filter_specialized<-globular_filter %>%
  filter(coexpression > 0.9,
        log2FC_mean_tissue >= 1,
        log2FC_sd_tissue >=1)

globular_filter_diverged<-globular_filter %>%
  filter(coexpression < 0.5,
        log2FC_mean_tissue >= 1,
        log2FC_sd_tissue >=1)

#assign the expression type to these gene pairs 
globular_filter_dosage_balance$expression_type<-"dosage_balance"
globular_filter_paralogue_dominance$expression_type<-"paralogue_dominance"
globular_filter_specialized$expression_type<-"specialized"
globular_filter_diverged$expression_type<-"diverged"

globular_expression_type<-rbind(globular_filter_dosage_balance, globular_filter_paralogue_dominance, globular_filter_specialized, globular_filter_diverged, globular_filter_one_express)

#extract the gene pairs not included in any of above expression type but both genes expressed 
globular_other_expression_type<- anti_join(globular_filter,globular_expression_type, by= "Gene_Pair")
globular_other_expression_type$expression_type<-"others"

#extract the gene pairs not expressed in this tissue 
globular_not_expressed<-anti_join(duplicated_gene_pairs,globular_filter, by="Gene_Pair")

#focus on the gene pairs with different expression types 

#this object includes the gene pairs expressed but with different expression patterns 
globular_expression_type_final<-rbind(globular_expression_type,globular_other_expression_type)
globular_expression_type_final<-left_join(globular_expression_type_final, duplicated_gene_pairs, by="Gene_Pair")

#this object includes all the gene pairs, including both expressed and not expressed ones
globular_expression_type_final_all<-left_join(duplicated_gene_pairs,globular_expression_type_final, by="Gene_Pair")
globular_expression_type_final_all$expression_type[is.na(globular_expression_type_final_all$expression_type)] <- "not_expressed"

globular_summary_expression_duplication <- globular_expression_type_final_all %>%
  group_by(type.x,expression_type) %>%
  summarise(count = n(), .groups = 'drop')  %>%
  group_by(type.x) %>%
  mutate(percentage = count / sum(count))

globular_summary_duplication <- globular_expression_type_final_all %>%
  group_by(expression_type,type.x) %>%
  summarise(count = n(), .groups = 'drop')  %>%
  group_by(expression_type) %>%
  mutate(percentage = count / sum(count))

globular_summary_expression <- globular_expression_type_final_all %>%
  group_by(expression_type) %>%
  summarise(count = n(), .groups = 'drop')  %>%
  group_by(expression_type) %>%
  mutate(percentage = count /11424)

#write.csv(globular_expression_type_final_all , "presentation_globular_expression_type_final_all.csv")

# Summary statistics by type
globular_summary_stats <- globular_expression_type_final %>%
  group_by(type) %>%
  summarise(
    coexpression_mean = mean(coexpression, na.rm = TRUE),
    coexpression_sd = sd(coexpression, na.rm = TRUE),
    log2FC_mean_mean = mean(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_mean_sd = sd(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_sd_mean = mean(log2FC_sd_tissue, na.rm = TRUE),
    log2FC_sd_sd = sd(log2FC_sd_tissue, na.rm = TRUE),
    .groups = 'drop'
  )

ggplot(globular_expression_type_final, aes(x = type, y = coexpression, fill = type)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
  theme_minimal() +
  labs(title = "Coexpression by Duplication Type", y = "Coexpression", x = "Duplication Type")

ggplot(globular_expression_type_final, aes(x = type, y = log2FC_mean_tissue, fill = type)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
  theme_minimal() +
  labs(title = "Mean log2FC by Duplication Type", y = "Mean log2FC", x = "Duplication Type")


ggplot(globular_expression_type_final, aes(x = type, y = log2FC_sd_tissue, fill = type)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
  theme_minimal() +
  labs(title = "log2FC SD by Duplication Type", y = "log2FC SD", x = "Duplication Type")


globular_expression_type_final_all_summary_set <- globular_expression_type_final_all %>% 
  group_by(fam.x) %>%
  summarise(
    count_not_expressed = sum(expression_type == "not_expressed", na.rm = TRUE),
    count_mono_expressed = sum(expression_type == "mono_expressed", na.rm = TRUE),
    has_recent_WGD_in_not_expressed = any(expression_type == "not_expressed" & type.x == "recent_WGD", na.rm = TRUE),
    coexpression_mean = mean(coexpression, na.rm = TRUE),
    coexpression_sd = sd(coexpression, na.rm = TRUE),
    log2FC_mean_mean = mean(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_mean_sd = sd(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_sd_mean = mean(log2FC_sd_tissue, na.rm = TRUE),
    log2FC_sd_sd = sd(log2FC_sd_tissue, na.rm = TRUE),
    .groups = 'drop'
  ) %>%
  mutate(
    set_expression = case_when(
      count_not_expressed == 6 & count_mono_expressed == 0 ~ "not expressed",
      count_not_expressed == 0 & count_mono_expressed == 3 ~ "three expressed",
      count_not_expressed == 1 & count_mono_expressed == 4 ~ "two expressed",
      count_not_expressed == 3 & count_mono_expressed == 3 ~ "one expressed",
      count_not_expressed == 0 & count_mono_expressed == 0 ~ "four expressed",
      TRUE ~ "other"
    ),
    set_expression = ifelse(
      set_expression == "two expressed" & has_recent_WGD_in_not_expressed,
      "recent_WGD_non_expressed",
      set_expression
    )
  )


summary_of_globular_expression_type_final_all_summary_set <- globular_expression_type_final_all_summary_set %>%
  count(set_expression, name = "family_count")

print(summary_of_globular_expression_type_final_all_summary_set)



globular_set_expression_summary_stats <- globular_expression_type_final_all_summary_set %>%
  group_by(set_expression) %>%
  summarise(
    n_families = n(),
    coexpression_mean = mean(coexpression_mean, na.rm = TRUE),
    coexpression_sd = sd(coexpression_mean, na.rm = TRUE),
    log2FC_mean_mean = mean(log2FC_mean_mean, na.rm = TRUE),
    log2FC_mean_sd = sd(log2FC_mean_mean, na.rm = TRUE),
    log2FC_sd_mean = mean(log2FC_sd_mean, na.rm = TRUE),
    log2FC_sd_sd = sd(log2FC_sd_mean, na.rm = TRUE),
    .groups = 'drop'
  )

p1 <- ggplot(globular_expression_type_final_all_summary_set, aes(x = set_expression, y = coexpression_mean, fill = set_expression)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA) +
  labs(title = "Coexpression Mean by Set Expression", y = "Mean Coexpression", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


p2 <- ggplot(globular_expression_type_final_all_summary_set, aes(x = set_expression, y = log2FC_mean_mean, fill = set_expression)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA) +
  labs(title = "log2FC Mean by Set Expression", y = "Mean log2FC", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p3 <- ggplot(globular_expression_type_final_all_summary_set, aes(x = set_expression, y = log2FC_sd_mean, fill = set_expression)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA) +
  labs(title = "log2FC SD by Set Expression", y = "SD of log2FC", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p1 / p2 / p3

```


```{r hypocotyl}
#load the data from last step, fold change calculation using the gene pairs at least one gene expressed 
hypocotyl_filter<-read.csv("set_hypocotyl_filter_paralog_pair_coexpression_fold_change.csv")

#load the normalized gene expression of gene pairs across different cell types within the tissue
#hypocotyl_filter_expression<-read.csv("07152025_expressed_hypocotyl_filtere_pairs_expression_separated_raw.csv")

#the gene pairs with fold change is equal to NA is the gene pairs with one gene expressed while the other not expressed
hypocotyl_filter_one_express<-hypocotyl_filter %>%
  filter(is.na(coexpression))

#assign the expression type to these gene pairs, one expressed while the other not 
hypocotyl_filter_one_express$expression_type<-"mono_expressed"

#extract the other types of expression patterns using fold change and coexpression information 
hypocotyl_filter_dosage_balance<-hypocotyl_filter %>%
  filter(coexpression > 0.9,
        log2FC_mean_tissue <1,
        log2FC_sd_tissue <1)

hypocotyl_filter_paralogue_dominance<-hypocotyl_filter %>%
  filter(coexpression > 0.9,
        log2FC_mean_tissue >= 1,
        log2FC_sd_tissue <1)

hypocotyl_filter_specialized<-hypocotyl_filter %>%
  filter(coexpression > 0.9,
        log2FC_mean_tissue >= 1,
        log2FC_sd_tissue >=1)

hypocotyl_filter_diverged<-hypocotyl_filter %>%
  filter(coexpression < 0.5,
        log2FC_mean_tissue >= 1,
        log2FC_sd_tissue >=1)

#assign the expression type to these gene pairs 
hypocotyl_filter_dosage_balance$expression_type<-"dosage_balance"
hypocotyl_filter_paralogue_dominance$expression_type<-"paralogue_dominance"
hypocotyl_filter_specialized$expression_type<-"specialized"
hypocotyl_filter_diverged$expression_type<-"diverged"

hypocotyl_expression_type<-rbind(hypocotyl_filter_dosage_balance, hypocotyl_filter_paralogue_dominance, hypocotyl_filter_specialized, hypocotyl_filter_diverged, hypocotyl_filter_one_express)

#extract the gene pairs not included in any of above expression type but both genes expressed 
hypocotyl_other_expression_type<- anti_join(hypocotyl_filter,hypocotyl_expression_type, by= "Gene_Pair")
hypocotyl_other_expression_type$expression_type<-"others"

#extract the gene pairs not expressed in this tissue 
hypocotyl_not_expressed<-anti_join(duplicated_gene_pairs,hypocotyl_filter, by="Gene_Pair")

#focus on the gene pairs with different expression types 

#this object includes the gene pairs expressed but with different expression patterns 
hypocotyl_expression_type_final<-rbind(hypocotyl_expression_type,hypocotyl_other_expression_type)
hypocotyl_expression_type_final<-left_join(hypocotyl_expression_type_final, duplicated_gene_pairs, by="Gene_Pair")

#this object includes all the gene pairs, including both expressed and not expressed ones
hypocotyl_expression_type_final_all<-left_join(duplicated_gene_pairs,hypocotyl_expression_type_final, by="Gene_Pair")
hypocotyl_expression_type_final_all$expression_type[is.na(hypocotyl_expression_type_final_all$expression_type)] <- "not_expressed"

hypocotyl_summary_expression_duplication <- hypocotyl_expression_type_final_all %>%
  group_by(type.x,expression_type) %>%
  summarise(count = n(), .groups = 'drop')  %>%
  group_by(type.x) %>%
  mutate(percentage = count / sum(count))

hypocotyl_summary_duplication <- hypocotyl_expression_type_final_all %>%
  group_by(expression_type,type.x) %>%
  summarise(count = n(), .groups = 'drop')  %>%
  group_by(expression_type) %>%
  mutate(percentage = count / sum(count))

hypocotyl_summary_expression <- hypocotyl_expression_type_final_all %>%
  group_by(expression_type) %>%
  summarise(count = n(), .groups = 'drop')  %>%
  group_by(expression_type) %>%
  mutate(percentage = count /11424)

#write.csv(hypocotyl_expression_type_final_all , "presentation_hypocotyl_expression_type_final_all.csv")


# Summary statistics by type
hypocotyl_summary_stats <- hypocotyl_expression_type_final %>%
  group_by(type) %>%
  summarise(
    coexpression_mean = mean(coexpression, na.rm = TRUE),
    coexpression_sd = sd(coexpression, na.rm = TRUE),
    log2FC_mean_mean = mean(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_mean_sd = sd(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_sd_mean = mean(log2FC_sd_tissue, na.rm = TRUE),
    log2FC_sd_sd = sd(log2FC_sd_tissue, na.rm = TRUE),
    .groups = 'drop'
  )

ggplot(hypocotyl_expression_type_final, aes(x = type, y = coexpression, fill = type)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
  theme_minimal() +
  labs(title = "Coexpression by Duplication Type", y = "Coexpression", x = "Duplication Type")

ggplot(hypocotyl_expression_type_final, aes(x = type, y = log2FC_mean_tissue, fill = type)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
  theme_minimal() +
  labs(title = "Mean log2FC by Duplication Type", y = "Mean log2FC", x = "Duplication Type")


ggplot(hypocotyl_expression_type_final, aes(x = type, y = log2FC_sd_tissue, fill = type)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
  theme_minimal() +
  labs(title = "log2FC SD by Duplication Type", y = "log2FC SD", x = "Duplication Type")



hypocotyl_expression_type_final_all_summary_set <- hypocotyl_expression_type_final_all %>% 
  group_by(fam.x) %>%
  summarise(
    count_not_expressed = sum(expression_type == "not_expressed", na.rm = TRUE),
    count_mono_expressed = sum(expression_type == "mono_expressed", na.rm = TRUE),
    has_recent_WGD_in_not_expressed = any(expression_type == "not_expressed" & type.x == "recent_WGD", na.rm = TRUE),
    coexpression_mean = mean(coexpression, na.rm = TRUE),
    coexpression_sd = sd(coexpression, na.rm = TRUE),
    log2FC_mean_mean = mean(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_mean_sd = sd(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_sd_mean = mean(log2FC_sd_tissue, na.rm = TRUE),
    log2FC_sd_sd = sd(log2FC_sd_tissue, na.rm = TRUE),
    .groups = 'drop'
  ) %>%
  mutate(
    set_expression = case_when(
      count_not_expressed == 6 & count_mono_expressed == 0 ~ "not expressed",
      count_not_expressed == 0 & count_mono_expressed == 3 ~ "three expressed",
      count_not_expressed == 1 & count_mono_expressed == 4 ~ "two expressed",
      count_not_expressed == 3 & count_mono_expressed == 3 ~ "one expressed",
      count_not_expressed == 0 & count_mono_expressed == 0 ~ "four expressed",
      TRUE ~ "other"
    ),
    set_expression = ifelse(
      set_expression == "two expressed" & has_recent_WGD_in_not_expressed,
      "recent_WGD_non_expressed",
      set_expression
    )
  )


summary_of_hypocotyl_expression_type_final_all_summary_set <- hypocotyl_expression_type_final_all_summary_set %>%
  count(set_expression, name = "family_count")

print(summary_of_hypocotyl_expression_type_final_all_summary_set)



hypocotyl_set_expression_summary_stats <- hypocotyl_expression_type_final_all_summary_set %>%
  group_by(set_expression) %>%
  summarise(
    n_families = n(),
    coexpression_mean = mean(coexpression_mean, na.rm = TRUE),
    coexpression_sd = sd(coexpression_mean, na.rm = TRUE),
    log2FC_mean_mean = mean(log2FC_mean_mean, na.rm = TRUE),
    log2FC_mean_sd = sd(log2FC_mean_mean, na.rm = TRUE),
    log2FC_sd_mean = mean(log2FC_sd_mean, na.rm = TRUE),
    log2FC_sd_sd = sd(log2FC_sd_mean, na.rm = TRUE),
    .groups = 'drop'
  )

p1 <- ggplot(hypocotyl_expression_type_final_all_summary_set, aes(x = set_expression, y = coexpression_mean, fill = set_expression)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA) +
  labs(title = "Coexpression Mean by Set Expression", y = "Mean Coexpression", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


p2 <- ggplot(hypocotyl_expression_type_final_all_summary_set, aes(x = set_expression, y = log2FC_mean_mean, fill = set_expression)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA) +
  labs(title = "log2FC Mean by Set Expression", y = "Mean log2FC", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p3 <- ggplot(hypocotyl_expression_type_final_all_summary_set, aes(x = set_expression, y = log2FC_sd_mean, fill = set_expression)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA) +
  labs(title = "log2FC SD by Set Expression", y = "SD of log2FC", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p1 / p2 / p3
```


```{r root}
#load the data from last step, fold change calculation using the gene pairs at least one gene expressed 
root_filter<-read.csv("set_root_filter_paralog_pair_coexpression_fold_change.csv")

#load the normalized gene expression of gene pairs across different cell types within the tissue
#root_filter_expression<-read.csv("07152025_expressed_root_filtere_pairs_expression_separated_raw.csv")

#the gene pairs with fold change is equal to NA is the gene pairs with one gene expressed while the other not expressed
root_filter_one_express<-root_filter %>%
  filter(is.na(coexpression))

#assign the expression type to these gene pairs, one expressed while the other not 
root_filter_one_express$expression_type<-"mono_expressed"

#extract the other types of expression patterns using fold change and coexpression information 
root_filter_dosage_balance<-root_filter %>%
  filter(coexpression > 0.9,
        log2FC_mean_tissue <1,
        log2FC_sd_tissue <1)

root_filter_paralogue_dominance<-root_filter %>%
  filter(coexpression > 0.9,
        log2FC_mean_tissue >= 1,
        log2FC_sd_tissue <1)

root_filter_specialized<-root_filter %>%
  filter(coexpression > 0.9,
        log2FC_mean_tissue >= 1,
        log2FC_sd_tissue >=1)

root_filter_diverged<-root_filter %>%
  filter(coexpression < 0.5,
        log2FC_mean_tissue >= 1,
        log2FC_sd_tissue >=1)

#assign the expression type to these gene pairs 
root_filter_dosage_balance$expression_type<-"dosage_balance"
root_filter_paralogue_dominance$expression_type<-"paralogue_dominance"
root_filter_specialized$expression_type<-"specialized"
root_filter_diverged$expression_type<-"diverged"

root_expression_type<-rbind(root_filter_dosage_balance, root_filter_paralogue_dominance, root_filter_specialized, root_filter_diverged, root_filter_one_express)

#extract the gene pairs not included in any of above expression type but both genes expressed 
root_other_expression_type<- anti_join(root_filter,root_expression_type, by= "Gene_Pair")
root_other_expression_type$expression_type<-"others"

#extract the gene pairs not expressed in this tissue 
root_not_expressed<-anti_join(duplicated_gene_pairs,root_filter, by="Gene_Pair")

#focus on the gene pairs with different expression types 

#this object includes the gene pairs expressed but with different expression patterns 
root_expression_type_final<-rbind(root_expression_type,root_other_expression_type)
root_expression_type_final<-left_join(root_expression_type_final, duplicated_gene_pairs, by="Gene_Pair")

#this object includes all the gene pairs, including both expressed and not expressed ones
root_expression_type_final_all<-left_join(duplicated_gene_pairs,root_expression_type_final, by="Gene_Pair")
root_expression_type_final_all$expression_type[is.na(root_expression_type_final_all$expression_type)] <- "not_expressed"


root_summary_expression_duplication <- root_expression_type_final_all %>%
  group_by(type.x,expression_type) %>%
  summarise(count = n(), .groups = 'drop')  %>%
  group_by(type.x) %>%
  mutate(percentage = count / sum(count))


root_summary_duplication <- root_expression_type_final_all %>%
  group_by(expression_type,type.x) %>%
  summarise(count = n(), .groups = 'drop')  %>%
  group_by(expression_type) %>%
  mutate(percentage = count / sum(count))


root_summary_expression <- root_expression_type_final_all %>%
  group_by(expression_type) %>%
  summarise(count = n(), .groups = 'drop')  %>%
  group_by(expression_type) %>%
  mutate(percentage = count /59351)

#write.csv(root_expression_type_final_all , "presentation_root_expression_type_final_all.csv")


# Summary statistics by type
root_summary_stats <- root_expression_type_final %>%
  group_by(type) %>%
  summarise(
    coexpression_mean = mean(coexpression, na.rm = TRUE),
    coexpression_sd = sd(coexpression, na.rm = TRUE),
    log2FC_mean_mean = mean(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_mean_sd = sd(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_sd_mean = mean(log2FC_sd_tissue, na.rm = TRUE),
    log2FC_sd_sd = sd(log2FC_sd_tissue, na.rm = TRUE),
    .groups = 'drop'
  )

ggplot(root_expression_type_final, aes(x = type, y = coexpression, fill = type)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
  theme_minimal() +
  labs(title = "Coexpression by Duplication Type", y = "Coexpression", x = "Duplication Type")

ggplot(root_expression_type_final, aes(x = type, y = log2FC_mean_tissue, fill = type)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
  theme_minimal() +
  labs(title = "Mean log2FC by Duplication Type", y = "Mean log2FC", x = "Duplication Type")


ggplot(root_expression_type_final, aes(x = type, y = log2FC_sd_tissue, fill = type)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
  theme_minimal() +
  labs(title = "log2FC SD by Duplication Type", y = "log2FC SD", x = "Duplication Type")


root_expression_type_final_all_summary_set <- root_expression_type_final_all %>% 
  group_by(fam.x) %>%
  summarise(
    count_not_expressed = sum(expression_type == "not_expressed", na.rm = TRUE),
    count_mono_expressed = sum(expression_type == "mono_expressed", na.rm = TRUE),
    has_recent_WGD_in_not_expressed = any(expression_type == "not_expressed" & type.x == "recent_WGD", na.rm = TRUE),
    coexpression_mean = mean(coexpression, na.rm = TRUE),
    coexpression_sd = sd(coexpression, na.rm = TRUE),
    log2FC_mean_mean = mean(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_mean_sd = sd(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_sd_mean = mean(log2FC_sd_tissue, na.rm = TRUE),
    log2FC_sd_sd = sd(log2FC_sd_tissue, na.rm = TRUE),
    .groups = 'drop'
  ) %>%
  mutate(
    set_expression = case_when(
      count_not_expressed == 6 & count_mono_expressed == 0 ~ "not expressed",
      count_not_expressed == 0 & count_mono_expressed == 3 ~ "three expressed",
      count_not_expressed == 1 & count_mono_expressed == 4 ~ "two expressed",
      count_not_expressed == 3 & count_mono_expressed == 3 ~ "one expressed",
      count_not_expressed == 0 & count_mono_expressed == 0 ~ "four expressed",
      TRUE ~ "other"
    ),
    set_expression = ifelse(
      set_expression == "two expressed" & has_recent_WGD_in_not_expressed,
      "recent_WGD_non_expressed",
      set_expression
    )
  )


summary_of_root_expression_type_final_all_summary_set <- root_expression_type_final_all_summary_set %>%
  count(set_expression, name = "family_count")

print(summary_of_root_expression_type_final_all_summary_set)



root_set_expression_summary_stats <- root_expression_type_final_all_summary_set %>%
  group_by(set_expression) %>%
  summarise(
    n_families = n(),
    coexpression_mean = mean(coexpression_mean, na.rm = TRUE),
    coexpression_sd = sd(coexpression_mean, na.rm = TRUE),
    log2FC_mean_mean = mean(log2FC_mean_mean, na.rm = TRUE),
    log2FC_mean_sd = sd(log2FC_mean_mean, na.rm = TRUE),
    log2FC_sd_mean = mean(log2FC_sd_mean, na.rm = TRUE),
    log2FC_sd_sd = sd(log2FC_sd_mean, na.rm = TRUE),
    .groups = 'drop'
  )

p1 <- ggplot(root_expression_type_final_all_summary_set, aes(x = set_expression, y = coexpression_mean, fill = set_expression)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA) +
  labs(title = "Coexpression Mean by Set Expression", y = "Mean Coexpression", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


p2 <- ggplot(root_expression_type_final_all_summary_set, aes(x = set_expression, y = log2FC_mean_mean, fill = set_expression)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA) +
  labs(title = "log2FC Mean by Set Expression", y = "Mean log2FC", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p3 <- ggplot(root_expression_type_final_all_summary_set, aes(x = set_expression, y = log2FC_sd_mean, fill = set_expression)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA) +
  labs(title = "log2FC SD by Set Expression", y = "SD of log2FC", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p1 / p2 / p3
```


```{r early_maturation}
#load the data from last step, fold change calculation using the gene pairs at least one gene expressed 
early_maturation_filter<-read.csv("set_early_maturation_filter_paralog_pair_coexpression_fold_change.csv")

#load the normalized gene expression of gene pairs across different cell types within the tissue
#early_maturation_filter_expression<-read.csv("07152025_expressed_early_maturation_filtere_pairs_expression_separated_raw.csv")

#the gene pairs with fold change is equal to NA is the gene pairs with one gene expressed while the other not expressed
early_maturation_filter_one_express<-early_maturation_filter %>%
  filter(is.na(coexpression))

#assign the expression type to these gene pairs, one expressed while the other not 
early_maturation_filter_one_express$expression_type<-"mono_expressed"

#extract the other types of expression patterns using fold change and coexpression information 
early_maturation_filter_dosage_balance<-early_maturation_filter %>%
  filter(coexpression > 0.9,
        log2FC_mean_tissue <1,
        log2FC_sd_tissue <1)

early_maturation_filter_paralogue_dominance<-early_maturation_filter %>%
  filter(coexpression > 0.9,
        log2FC_mean_tissue >= 1,
        log2FC_sd_tissue <1)

early_maturation_filter_specialized<-early_maturation_filter %>%
  filter(coexpression > 0.9,
        log2FC_mean_tissue >= 1,
        log2FC_sd_tissue >=1)

early_maturation_filter_diverged<-early_maturation_filter %>%
  filter(coexpression < 0.5,
        log2FC_mean_tissue >= 1,
        log2FC_sd_tissue >=1)

#assign the expression type to these gene pairs 
early_maturation_filter_dosage_balance$expression_type<-"dosage_balance"
early_maturation_filter_paralogue_dominance$expression_type<-"paralogue_dominance"
early_maturation_filter_specialized$expression_type<-"specialized"
early_maturation_filter_diverged$expression_type<-"diverged"

early_maturation_expression_type<-rbind(early_maturation_filter_dosage_balance, early_maturation_filter_paralogue_dominance, early_maturation_filter_specialized, early_maturation_filter_diverged, early_maturation_filter_one_express)

#extract the gene pairs not included in any of above expression type but both genes expressed 
early_maturation_other_expression_type<- anti_join(early_maturation_filter,early_maturation_expression_type, by= "Gene_Pair")
early_maturation_other_expression_type$expression_type<-"others"

#extract the gene pairs not expressed in this tissue 
early_maturation_not_expressed<-anti_join(duplicated_gene_pairs,early_maturation_filter, by="Gene_Pair")

#focus on the gene pairs with different expression types 

#this object includes the gene pairs expressed but with different expression patterns 
early_maturation_expression_type_final<-rbind(early_maturation_expression_type,early_maturation_other_expression_type)
early_maturation_expression_type_final<-left_join(early_maturation_expression_type_final, duplicated_gene_pairs, by="Gene_Pair")

#this object includes all the gene pairs, including both expressed and not expressed ones
early_maturation_expression_type_final_all<-left_join(duplicated_gene_pairs,early_maturation_expression_type_final, by="Gene_Pair")
early_maturation_expression_type_final_all$expression_type[is.na(early_maturation_expression_type_final_all$expression_type)] <- "not_expressed"


early_maturation_summary_expression_duplication <- early_maturation_expression_type_final_all %>%
  group_by(type.x,expression_type) %>%
  summarise(count = n(), .groups = 'drop')  %>%
  group_by(type.x) %>%
  mutate(percentage = count / sum(count))


early_maturation_summary_duplication <- early_maturation_expression_type_final_all %>%
  group_by(expression_type,type.x) %>%
  summarise(count = n(), .groups = 'drop')  %>%
  group_by(expression_type) %>%
  mutate(percentage = count / sum(count))


early_maturation_summary_expression <- early_maturation_expression_type_final_all %>%
  group_by(expression_type) %>%
  summarise(count = n(), .groups = 'drop')  %>%
  group_by(expression_type) %>%
  mutate(percentage = count /11424)

#write.csv(early_maturation_expression_type_final_all , "presentation_early_maturation_expression_type_final_all.csv")

# Summary statistics by type
early_maturation_summary_stats <- early_maturation_expression_type_final %>%
  group_by(type) %>%
  summarise(
    coexpression_mean = mean(coexpression, na.rm = TRUE),
    coexpression_sd = sd(coexpression, na.rm = TRUE),
    log2FC_mean_mean = mean(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_mean_sd = sd(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_sd_mean = mean(log2FC_sd_tissue, na.rm = TRUE),
    log2FC_sd_sd = sd(log2FC_sd_tissue, na.rm = TRUE),
    .groups = 'drop'
  )

ggplot(early_maturation_expression_type_final, aes(x = type, y = coexpression, fill = type)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
  theme_minimal() +
  labs(title = "Coexpression by Duplication Type", y = "Coexpression", x = "Duplication Type")

ggplot(early_maturation_expression_type_final, aes(x = type, y = log2FC_mean_tissue, fill = type)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
  theme_minimal() +
  labs(title = "Mean log2FC by Duplication Type", y = "Mean log2FC", x = "Duplication Type")


ggplot(early_maturation_expression_type_final, aes(x = type, y = log2FC_sd_tissue, fill = type)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
  theme_minimal() +
  labs(title = "log2FC SD by Duplication Type", y = "log2FC SD", x = "Duplication Type")


early_maturation_expression_type_final_all_summary_set <- early_maturation_expression_type_final_all %>% 
  group_by(fam.x) %>%
  summarise(
    count_not_expressed = sum(expression_type == "not_expressed", na.rm = TRUE),
    count_mono_expressed = sum(expression_type == "mono_expressed", na.rm = TRUE),
    has_recent_WGD_in_not_expressed = any(expression_type == "not_expressed" & type.x == "recent_WGD", na.rm = TRUE),
    coexpression_mean = mean(coexpression, na.rm = TRUE),
    coexpression_sd = sd(coexpression, na.rm = TRUE),
    log2FC_mean_mean = mean(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_mean_sd = sd(log2FC_mean_tissue, na.rm = TRUE),
    log2FC_sd_mean = mean(log2FC_sd_tissue, na.rm = TRUE),
    log2FC_sd_sd = sd(log2FC_sd_tissue, na.rm = TRUE),
    .groups = 'drop'
  ) %>%
  mutate(
    set_expression = case_when(
      count_not_expressed == 6 & count_mono_expressed == 0 ~ "not expressed",
      count_not_expressed == 0 & count_mono_expressed == 3 ~ "three expressed",
      count_not_expressed == 1 & count_mono_expressed == 4 ~ "two expressed",
      count_not_expressed == 3 & count_mono_expressed == 3 ~ "one expressed",
      count_not_expressed == 0 & count_mono_expressed == 0 ~ "four expressed",
      TRUE ~ "other"
    ),
    set_expression = ifelse(
      set_expression == "two expressed" & has_recent_WGD_in_not_expressed,
      "recent_WGD_non_expressed",
      set_expression
    )
  )


summary_of_early_maturation_expression_type_final_all_summary_set <- early_maturation_expression_type_final_all_summary_set %>%
  count(set_expression, name = "family_count")

print(summary_of_early_maturation_expression_type_final_all_summary_set)



early_maturation_set_expression_summary_stats <- early_maturation_expression_type_final_all_summary_set %>%
  group_by(set_expression) %>%
  summarise(
    n_families = n(),
    coexpression_mean = mean(coexpression_mean, na.rm = TRUE),
    coexpression_sd = sd(coexpression_mean, na.rm = TRUE),
    log2FC_mean_mean = mean(log2FC_mean_mean, na.rm = TRUE),
    log2FC_mean_sd = sd(log2FC_mean_mean, na.rm = TRUE),
    log2FC_sd_mean = mean(log2FC_sd_mean, na.rm = TRUE),
    log2FC_sd_sd = sd(log2FC_sd_mean, na.rm = TRUE),
    .groups = 'drop'
  )

p1 <- ggplot(early_maturation_expression_type_final_all_summary_set, aes(x = set_expression, y = coexpression_mean, fill = set_expression)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA) +
  labs(title = "Coexpression Mean by Set Expression", y = "Mean Coexpression", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


p2 <- ggplot(early_maturation_expression_type_final_all_summary_set, aes(x = set_expression, y = log2FC_mean_mean, fill = set_expression)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA) +
  labs(title = "log2FC Mean by Set Expression", y = "Mean log2FC", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p3 <- ggplot(early_maturation_expression_type_final_all_summary_set, aes(x = set_expression, y = log2FC_sd_mean, fill = set_expression)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA) +
  labs(title = "log2FC SD by Set Expression", y = "SD of log2FC", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p1 / p2 / p3


```

```{r write the csv files}
write.csv(cotyledon_expression_type_final_all, "08022025_cotyledon_expression_type_final_all.csv")
write.csv(cotyledon_expression_type_final_all_summary_set, "08022025_cotyledon_expression_type_final_all_summary_set.csv")
write.csv(early_nodule_expression_type_final_all, "08022025_early_nodule_expression_type_final_all.csv")
write.csv(early_nodule_expression_type_final_all_summary_set, "08022025_early_nodule_expression_type_final_all_summary_set.csv")
write.csv(early_maturation_expression_type_final_all, "08022025_early_maturation_expression_type_final_all.csv")
write.csv(early_maturation_expression_type_final_all_summary_set, "08022025_early_maturation_expression_type_final_all_summary_set.csv")
write.csv(root_expression_type_final_all, "08022025_root_expression_type_final_all.csv")
write.csv(root_expression_type_final_all_summary_set, "08022025_root_expression_type_final_all_summary_set.csv")
write.csv(hypocotyl_expression_type_final_all, "08022025_hypocotyl_expression_type_final_all.csv")
write.csv(hypocotyl_expression_type_final_all_summary_set, "08022025_hypocotyl_expression_type_final_all_summary_set.csv")
write.csv(heart_expression_type_final_all, "08022025_heart_expression_type_final_all.csv")
write.csv(heart_expression_type_final_all_summary_set, "08022025_heart_expression_type_final_all_summary_set.csv")
write.csv(globular_expression_type_final_all, "08022025_globular_expression_type_final_all.csv")
write.csv(globular_expression_type_final_all_summary_set, "08022025_globular_expression_type_final_all_summary_set.csv")


write.csv(summary_of_cotyledon_expression_type_final_all_summary_set, "08022025_summary_of_cotyledon_expression_type_final_all_summary_set.csv")
write.csv(summary_of_early_maturation_expression_type_final_all_summary_set, "08022025_summary_of_early_maturation_expression_type_final_all_summary_set.csv")
write.csv(summary_of_early_nodule_expression_type_final_all_summary_set, "08022025_summary_of_early_nodule_expression_type_final_all_summary_set.csv")
write.csv(summary_of_heart_expression_type_final_all_summary_set, "08022025_summary_of_heart_expression_type_final_all_summary_set.csv")
write.csv(summary_of_hypocotyl_expression_type_final_all_summary_set, "08022025_summary_of_hypocotyl_expression_type_final_all_summary_set.csv")
write.csv(summary_of_root_expression_type_final_all_summary_set, "08022025_summary_of_root_expression_type_final_all_summary_set.csv")
write.csv(summary_of_globular_expression_type_final_all_summary_set, "08022025_summary_of_globular_expression_type_final_all_summary_set.csv")

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
