---
title: "fold_change"
output: html_document
date: "2024-11-21"
---

```{r early_nodule}
### ........................................................... ###
### script to calculate the fold-change in expression of a paralog
### pair across samples
###
### mean and standard deviation of log2-transformed fold-changes
### are used to define the duplicate gene retention categories
### ........................................................... ###

# get distribution of fold changes for shortlisted tissues for paralog pair
get_FC_dist <- function(gene1, gene2, tissue_list, exp){
  fold_change <- as.vector(log2(exp[gene1, tissue_list]/exp[gene2, tissue_list]))
  return(fold_change)
}

# main function to calculate the fold-change in expression of a pair
# of genes across tissue samples

  # list of species
  spename = c('set_early_nodule')
  
  # load expression data

  exp1 = read.csv("07152025_early_nodule_filter_normalized.csv", row.names = 1)
  exp1 <- as.matrix(exp1)

  # load table of paralog pairs
  df = read.delim(('set_early_nodule_filter_coexp_network_paralog_pair_coexpression.csv'), sep = ',', check.names = F)
  df$log2FC_mean_tissue = NA
  df$log2FC_sd_tissue = NA
  
  # for coexpressed pairs, find new cor with shortlisted tissues and FC-dist
  options(warn = -1)
  
  for(ii in 1:dim(df)[1]){
    g1 = df$Gene1[ii]
    g2 = df$Gene2[ii]
    
    # subset to paralog pairs with some coexpression in the coexp network
    if(!is.na(df$coexpression[ii])){
      
      # retain samples with total expression of paralog pair > 2 TPM, and
      # expression of each paralog > 0
      
      ids = which(colSums(exp1[c(g1, g2),])>=2 & exp1[g1,]>0 & exp1[g2,]>0)  
      fold_change <- get_FC_dist(g1, g2, ids, exp1)
      
      df$log2FC_mean_tissue[ii] <- mean(abs(fold_change))
      df$log2FC_sd_tissue[ii] <- sd(fold_change)
    }       
  }
  
  # save
  write.table(df, paste0(spename, '_filter_paralog_pair_coexpression_fold_change.csv'), 
              sep = ',', row.names = F, col.names = T, quote = F)
  

na_count <- sum(is.na(df$coexpression))
```


```{r cotyledon}
### ........................................................... ###
### script to calculate the fold-change in expression of a paralog
### pair across samples
###
### mean and standard deviation of log2-transformed fold-changes
### are used to define the duplicate gene retention categories
### ........................................................... ###

# get distribution of fold changes for shortlisted tissues for paralog pair
get_FC_dist <- function(gene1, gene2, tissue_list, exp){
  fold_change <- as.vector(log2(exp[gene1, tissue_list]/exp[gene2, tissue_list]))
  return(fold_change)
}

# main function to calculate the fold-change in expression of a pair
# of genes across tissue samples

  # list of species
  spename = c('set_cotyledon')
  
  # load expression data

  exp1 = read.csv("07152025_cotyledon_filter_normalized.csv", row.names = 1)
  exp1 <- as.matrix(exp1)

  # load table of paralog pairs
  df = read.delim(('set_cotyledon_filter_coexp_network_paralog_pair_coexpression.csv'), sep = ',', check.names = F)
  df$log2FC_mean_tissue = NA
  df$log2FC_sd_tissue = NA
  
  # for coexpressed pairs, find new cor with shortlisted tissues and FC-dist
  options(warn = -1)
  
  for(ii in 1:dim(df)[1]){
    g1 = df$Gene1[ii]
    g2 = df$Gene2[ii]
    
    # subset to paralog pairs with some coexpression in the coexp network
    if(!is.na(df$coexpression[ii])){
      
      # retain samples with total expression of paralog pair > 2 TPM, and
      # expression of each paralog > 0
      
      ids = which(colSums(exp1[c(g1, g2),])>=2 & exp1[g1,]>0 & exp1[g2,]>0)  
      fold_change <- get_FC_dist(g1, g2, ids, exp1)
      
      df$log2FC_mean_tissue[ii] <- mean(abs(fold_change))
      df$log2FC_sd_tissue[ii] <- sd(fold_change)
    }       
  }
  
  # save
  write.table(df, paste0(spename, '_filter_paralog_pair_coexpression_fold_change.csv'), 
              sep = ',', row.names = F, col.names = T, quote = F)
  

na_count <- sum(is.na(df$coexpression))
```

```{r early maturation}
### ........................................................... ###
### script to calculate the fold-change in expression of a paralog
### pair across samples
###
### mean and standard deviation of log2-transformed fold-changes
### are used to define the duplicate gene retention categories
### ........................................................... ###

# get distribution of fold changes for shortlisted tissues for paralog pair
get_FC_dist <- function(gene1, gene2, tissue_list, exp){
  fold_change <- as.vector(log2(exp[gene1, tissue_list]/exp[gene2, tissue_list]))
  return(fold_change)
}

# main function to calculate the fold-change in expression of a pair
# of genes across tissue samples

  # list of species
  spename = c('set_early_maturation')
  
  # load expression data

  exp1 = read.csv("07152025_early_maturation_filter_normalized.csv", row.names = 1)
  exp1 <- as.matrix(exp1)

  # load table of paralog pairs
  df = read.delim(('set_early_maturation_filter_coexp_network_paralog_pair_coexpression.csv'), sep = ',', check.names = F)
  df$log2FC_mean_tissue = NA
  df$log2FC_sd_tissue = NA
  
  # for coexpressed pairs, find new cor with shortlisted tissues and FC-dist
  options(warn = -1)
  
  for(ii in 1:dim(df)[1]){
    g1 = df$Gene1[ii]
    g2 = df$Gene2[ii]
    
    # subset to paralog pairs with some coexpression in the coexp network
    if(!is.na(df$coexpression[ii])){
      
      # retain samples with total expression of paralog pair > 2 TPM, and
      # expression of each paralog > 0
      
      ids = which(colSums(exp1[c(g1, g2),])>=2 & exp1[g1,]>0 & exp1[g2,]>0)  
      fold_change <- get_FC_dist(g1, g2, ids, exp1)
      
      df$log2FC_mean_tissue[ii] <- mean(abs(fold_change))
      df$log2FC_sd_tissue[ii] <- sd(fold_change)
    }       
  }
  
  # save
  write.table(df, paste0(spename, '_filter_paralog_pair_coexpression_fold_change.csv'), 
              sep = ',', row.names = F, col.names = T, quote = F)
  

na_count <- sum(is.na(df$coexpression))
```

```{r globular}
### ........................................................... ###
### script to calculate the fold-change in expression of a paralog
### pair across samples
###
### mean and standard deviation of log2-transformed fold-changes
### are used to define the duplicate gene retention categories
### ........................................................... ###

# get distribution of fold changes for shortlisted tissues for paralog pair
get_FC_dist <- function(gene1, gene2, tissue_list, exp){
  fold_change <- as.vector(log2(exp[gene1, tissue_list]/exp[gene2, tissue_list]))
  return(fold_change)
}

# main function to calculate the fold-change in expression of a pair
# of genes across tissue samples

  # list of species
  spename = c('set_globular')
  
  # load expression data

  exp1 = read.csv("07152025_globular_filter_normalized.csv", row.names = 1)
  exp1 <- as.matrix(exp1)

  # load table of paralog pairs
  df = read.delim(('set_globular_filter_coexp_network_paralog_pair_coexpression.csv'), sep = ',', check.names = F)
  df$log2FC_mean_tissue = NA
  df$log2FC_sd_tissue = NA
  
  # for coexpressed pairs, find new cor with shortlisted tissues and FC-dist
  options(warn = -1)
  
  for(ii in 1:dim(df)[1]){
    g1 = df$Gene1[ii]
    g2 = df$Gene2[ii]
    
    # subset to paralog pairs with some coexpression in the coexp network
    if(!is.na(df$coexpression[ii])){
      
      # retain samples with total expression of paralog pair > 2 TPM, and
      # expression of each paralog > 0
      
      ids = which(colSums(exp1[c(g1, g2),])>=2 & exp1[g1,]>0 & exp1[g2,]>0)  
      fold_change <- get_FC_dist(g1, g2, ids, exp1)
      
      df$log2FC_mean_tissue[ii] <- mean(abs(fold_change))
      df$log2FC_sd_tissue[ii] <- sd(fold_change)
    }       
  }
  
  # save
  write.table(df, paste0(spename, '_filter_paralog_pair_coexpression_fold_change.csv'), 
              sep = ',', row.names = F, col.names = T, quote = F)
  

na_count <- sum(is.na(df$coexpression))
```

```{r hypocotyl}
### ........................................................... ###
### script to calculate the fold-change in expression of a paralog
### pair across samples
###
### mean and standard deviation of log2-transformed fold-changes
### are used to define the duplicate gene retention categories
### ........................................................... ###

# get distribution of fold changes for shortlisted tissues for paralog pair
get_FC_dist <- function(gene1, gene2, tissue_list, exp){
  fold_change <- as.vector(log2(exp[gene1, tissue_list]/exp[gene2, tissue_list]))
  return(fold_change)
}

# main function to calculate the fold-change in expression of a pair
# of genes across tissue samples

  # list of species
  spename = c('set_hypocotyl')
  
  # load expression data

  exp1 = read.csv("07152025_hypocotyl_filter_normalized.csv", row.names = 1)
  exp1 <- as.matrix(exp1)

  # load table of paralog pairs
  df = read.delim(('set_hypocotyl_filter_coexp_network_paralog_pair_coexpression.csv'), sep = ',', check.names = F)
  df$log2FC_mean_tissue = NA
  df$log2FC_sd_tissue = NA
  
  # for coexpressed pairs, find new cor with shortlisted tissues and FC-dist
  options(warn = -1)
  
  for(ii in 1:dim(df)[1]){
    g1 = df$Gene1[ii]
    g2 = df$Gene2[ii]
    
    # subset to paralog pairs with some coexpression in the coexp network
    if(!is.na(df$coexpression[ii])){
      
      # retain samples with total expression of paralog pair > 2 TPM, and
      # expression of each paralog > 0
      
      ids = which(colSums(exp1[c(g1, g2),])>=2 & exp1[g1,]>0 & exp1[g2,]>0)  
      fold_change <- get_FC_dist(g1, g2, ids, exp1)
      
      df$log2FC_mean_tissue[ii] <- mean(abs(fold_change))
      df$log2FC_sd_tissue[ii] <- sd(fold_change)
    }       
  }
  
  # save
  write.table(df, paste0(spename, '_filter_paralog_pair_coexpression_fold_change.csv'), 
              sep = ',', row.names = F, col.names = T, quote = F)
  

na_count <- sum(is.na(df$coexpression))
```

```{r heart}
### ........................................................... ###
### script to calculate the fold-change in expression of a paralog
### pair across samples
###
### mean and standard deviation of log2-transformed fold-changes
### are used to define the duplicate gene retention categories
### ........................................................... ###

# get distribution of fold changes for shortlisted tissues for paralog pair
get_FC_dist <- function(gene1, gene2, tissue_list, exp){
  fold_change <- as.vector(log2(exp[gene1, tissue_list]/exp[gene2, tissue_list]))
  return(fold_change)
}

# main function to calculate the fold-change in expression of a pair
# of genes across tissue samples

  # list of species
  spename = c('set_heart')
  
  # load expression data

  exp1 = read.csv("07152025_heart_filter_normalized.csv", row.names = 1)
  exp1 <- as.matrix(exp1)

  # load table of paralog pairs
  df = read.delim(('set_heart_filter_coexp_network_paralog_pair_coexpression.csv'), sep = ',', check.names = F)
  df$log2FC_mean_tissue = NA
  df$log2FC_sd_tissue = NA
  
  # for coexpressed pairs, find new cor with shortlisted tissues and FC-dist
  options(warn = -1)
  
  for(ii in 1:dim(df)[1]){
    g1 = df$Gene1[ii]
    g2 = df$Gene2[ii]
    
    # subset to paralog pairs with some coexpression in the coexp network
    if(!is.na(df$coexpression[ii])){
      
      # retain samples with total expression of paralog pair > 2 TPM, and
      # expression of each paralog > 0
      
      ids = which(colSums(exp1[c(g1, g2),])>=2 & exp1[g1,]>0 & exp1[g2,]>0)  
      fold_change <- get_FC_dist(g1, g2, ids, exp1)
      
      df$log2FC_mean_tissue[ii] <- mean(abs(fold_change))
      df$log2FC_sd_tissue[ii] <- sd(fold_change)
    }       
  }
  
  # save
  write.table(df, paste0(spename, '_filter_paralog_pair_coexpression_fold_change.csv'), 
              sep = ',', row.names = F, col.names = T, quote = F)
  

na_count <- sum(is.na(df$coexpression))
```

```{r root}
### ........................................................... ###
### script to calculate the fold-change in expression of a paralog
### pair across samples
###
### mean and standard deviation of log2-transformed fold-changes
### are used to define the duplicate gene retention categories
### ........................................................... ###

# get distribution of fold changes for shortlisted tissues for paralog pair
get_FC_dist <- function(gene1, gene2, tissue_list, exp){
  fold_change <- as.vector(log2(exp[gene1, tissue_list]/exp[gene2, tissue_list]))
  return(fold_change)
}

# main function to calculate the fold-change in expression of a pair
# of genes across tissue samples

  # list of species
  spename = c('set_root')
  
  # load expression data

  exp1 = read.csv("07152025_root_filter_normalized.csv", row.names = 1)
  exp1 <- as.matrix(exp1)

  # load table of paralog pairs
  df = read.delim(('set_root_filter_coexp_network_paralog_pair_coexpression.csv'), sep = ',', check.names = F)
  df$log2FC_mean_tissue = NA
  df$log2FC_sd_tissue = NA
  
  # for coexpressed pairs, find new cor with shortlisted tissues and FC-dist
  options(warn = -1)
  
  for(ii in 1:dim(df)[1]){
    g1 = df$Gene1[ii]
    g2 = df$Gene2[ii]
    
    # subset to paralog pairs with some coexpression in the coexp network
    if(!is.na(df$coexpression[ii])){
      
      # retain samples with total expression of paralog pair > 2 TPM, and
      # expression of each paralog > 0
      
      ids = which(colSums(exp1[c(g1, g2),])>=2 & exp1[g1,]>0 & exp1[g2,]>0)  
      fold_change <- get_FC_dist(g1, g2, ids, exp1)
      
      df$log2FC_mean_tissue[ii] <- mean(abs(fold_change))
      df$log2FC_sd_tissue[ii] <- sd(fold_change)
    }       
  }
  
  # save
  write.table(df, paste0(spename, '_filter_paralog_pair_coexpression_fold_change.csv'), 
              sep = ',', row.names = F, col.names = T, quote = F)
  

na_count <- sum(is.na(df$coexpression))
```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
